import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./nopage/components/navbar"
import Footer from "./nopage/components/footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Creasto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
